spring:
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      open-in-view: false
      database-platform: org.hibernate.dialect.MariaDBDialect

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ojeommo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    sql:
      init:
        mode: always
jwt:
  issuer: ojeommo
  secret_key: aaaaaaaabaaaaaaaaaaaaabaaaaaaaaabaaaaaaaaaa
#  비밀키 값 추후에 환경변수로 옮길 것.