spring:
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      open-in-view: false
      database-platform: org.hibernate.dialect.MariaDBDialect

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false
    prefix : "file:src/main/resources/templates/"



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ojeommo
    #    username: ${DB_USERNAME}
    #    password: ${DB_PASSWORD}
    username: root
    password: root

    sql:
      init:
        mode: always

    thymeleaf:
      prefix: classpath:templates/
      suffix: .html
      check-template-location: true
      mode: HTML
      cache: false