spring:
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 100
      open-in-view: false
      database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: create #이거 키면 DB의 테이블 다 날리고 새로생김

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    cache: false
    prefix : "file:src/main/resources/templates/"



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ojeommo

  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

    sql:
      init:
        mode: always

    thymeleaf:
      prefix=classpath: templates/
      suffix: .html
      check-template-location: true
      cache: false
      mvc:
        static-path-pattern: "/static/**"

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

#  비밀키 값 추후에 환경변수로 옮길 것.